# Generated by Django 4.2.30 on 2026-09-15 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='Computer Science', max_length=100)),
                ('room_number', models.CharField(default='Room 101', max_length=20)),
                ('status', models.CharField(choices=[('IN_OFFICE', 'In-Office'), ('IN_CLASS', 'In-Class'), ('ON_BREAK', 'On-Break'), ('OUT', 'Out of Office')], default='OUT', max_length=20)),
                ('back_at', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
