# Generated by Django 6.1.1 on 2026-09-22 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_profile_bio_profile_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('department', models.CharField(blank=True, choices=[('CCS', 'College of Computer Studies'), ('CEA', 'College of Engineering and Architecture'), ('CASE', 'College of Arts, Sciences, and Education'), ('CMBA', 'College of Management, Business, and Accountancy'), ('CCJ', 'College of Criminal Justice'), ('CNAHS', 'College of Nursing and Allied Health Sciences')], max_length=20, null=True)),
                ('default_room_number', models.CharField(blank=True, max_length=20, null=True)),
                ('default_office_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('department', models.CharField(blank=True, choices=[('CCS', 'College of Computer Studies'), ('CEA', 'College of Engineering and Architecture'), ('CASE', 'College of Arts, Sciences, and Education'), ('CMBA', 'College of Management, Business, and Accountancy'), ('CCJ', 'College of Criminal Justice'), ('CNAHS', 'College of Nursing and Allied Health Sciences')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
