# Generated by Django 6.1.1 on 2026-09-22 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_facultyprofile_studentprofile_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultyprofile',
            old_name='default_office_hours',
            new_name='office_hours',
        ),
        migrations.RenameField(
            model_name='facultyprofile',
            old_name='default_room_number',
            new_name='office_room',
        ),
    ]
